# Generated by Django 5.2.14 on 2026-05-26 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "iata_code",
                    models.CharField(
                        help_text="3-letter airport code e.g. SFO",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("city", models.CharField(max_length=255)),
                (
                    "country",
                    models.CharField(help_text="2-letter country code", max_length=2),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_row_index",
                    models.IntegerField(
                        help_text="Line or element index inside the raw data source"
                    ),
                ),
                (
                    "unique_transaction_id",
                    models.CharField(
                        help_text="Source system ID, e.g. booking ID, document number",
                        max_length=100,
                    ),
                ),
                (
                    "scope_category",
                    models.CharField(
                        choices=[
                            (
                                "SCOPE_1_STATIONARY",
                                "Scope 1: Stationary Combustion (Fuel)",
                            ),
                            ("SCOPE_2_ELECTRICITY", "Scope 2: Purchased Electricity"),
                            (
                                "SCOPE_3_TRAVEL",
                                "Scope 3 Category 6: Employee Business Travel",
                            ),
                            (
                                "SCOPE_3_PROCUREMENT",
                                "Scope 3 Category 1: Purchased Goods",
                            ),
                            (
                                "EXCLUDED_LOGISTICS",
                                "Excluded: Internal Logistical Transfer",
                            ),
                            (
                                "EXCLUDED_AVOIDED",
                                "Excluded: Solar Export / Avoided Emissions",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="Calculated activity start date in UTC"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="Calculated activity end date in UTC"
                    ),
                ),
                (
                    "raw_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity exactly as extracted",
                        max_digits=18,
                    ),
                ),
                (
                    "raw_unit",
                    models.CharField(
                        help_text="Original unit as extracted, e.g. GAL, MWh, TO",
                        max_length=50,
                    ),
                ),
                (
                    "normalized_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Standardized baseline quantity",
                        max_digits=18,
                    ),
                ),
                (
                    "normalized_unit",
                    models.CharField(
                        choices=[
                            ("LITERS", "Liters"),
                            ("KWH", "Kilowatt-Hours"),
                            ("PASSENGER_KM", "Passenger-Kilometers"),
                            ("METRIC_TONS", "Metric Tons"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resolved_facility_id",
                    models.CharField(
                        blank=True,
                        help_text="Opaque facility ID mapped during lookup",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resolved_facility_country",
                    models.CharField(
                        help_text="Resolved 2-letter country code", max_length=2
                    ),
                ),
                (
                    "workflow_status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending Analyst Review"),
                            ("APPROVED", "Approved by Analyst"),
                            ("REJECTED", "Rejected / Excluded"),
                            ("LOCKED_FOR_AUDIT", "Locked for Final Audit"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=30,
                    ),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(
                        default=False,
                        help_text="True if parsing flagged anomalies or validation issues",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Parser-level failure or suspicion details",
                    ),
                ),
                (
                    "analyst_notes",
                    models.TextField(
                        blank=True,
                        help_text="Compulsory notes for editing or overrides",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deduplication_key",
                    models.CharField(
                        help_text="Dynamic hashing of txn_id, date, and scope",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawPayload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("SAP_ODATA", "SAP OData API"),
                            ("SAP_IDOC", "SAP Legacy XML IDoc"),
                            ("SAP_CSV", "SAP Procurement CSV"),
                            ("SAP_XLSX", "SAP Fuel Consumption Excel"),
                            ("UTILITY_IN_CSV", "Indian Utility Smart Meter CSV"),
                            ("UTILITY_UK_CSV", "UK Utility aggregate CSV"),
                            ("TRAVEL_CSV", "Concur-style Travel CSV"),
                            ("CONCUR_JSON", "Concur Itinerary API JSON"),
                            ("NAVAN_JSON", "Navan TMC API JSON"),
                        ],
                        max_length=50,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payload_content",
                    models.TextField(
                        help_text="Stores the exact raw upload text or JSON representation"
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        help_text="SHA-256 integrity checksum to prevent tempering",
                        max_length=64,
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingested_by",
                    models.CharField(
                        help_text="Identity of the analyst or pipeline", max_length=150
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created via Ingestion"),
                            ("EDIT", "Modified by Analyst"),
                            ("APPROVE", "Approved by Analyst"),
                            ("REJECT", "Rejected by Analyst"),
                            ("LOCK", "Locked for Audits"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        help_text="Identity of the active user", max_length=150
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "previous_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of fields before modification",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of fields after modification",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Mandatory analyst explanation for overrides"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core_api.normalizedactivity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="raw_payload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="normalized_activities",
                to="core_api.rawpayload",
            ),
        ),
        migrations.AddField(
            model_name="rawpayload",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_payloads",
                to="core_api.tenant",
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="normalized_activities",
                to="core_api.tenant",
            ),
        ),
    ]
