# Generated by Django 5.2.14 on 2026-05-26 12:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_api", "0002_seed_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="activity_unit",
            field=models.CharField(
                blank=True, help_text="Raw quantity unit", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="activity_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Raw quantity value",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="approved_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Category e.g. fuel, electricity, flights, hotels, ground",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="emission_factor",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="emission_factor_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="flag_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="normalized_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Normalized emission in kgCO2e",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="normalized_value_unit",
            field=models.CharField(
                default="kgCO2e",
                help_text="Emission unit, always kgCO2e",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="raw_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Source raw row JSON content"
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="scope",
            field=models.CharField(
                blank=True, help_text="Scope e.g. 1/2/3", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="source_row_id",
            field=models.CharField(
                blank=True, help_text="Unique row hash", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="status",
            field=models.CharField(default="PENDING_REVIEW", max_length=50),
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tenant",
            name="slug",
            field=models.CharField(default="tata-motors", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="changed_by",
            field=models.CharField(
                help_text="Identity of the active user as string", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="normalizedactivity",
            name="approved_by",
            field=models.CharField(
                blank=True,
                help_text="Compat string for user email",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="normalizedactivity",
            name="raw_payload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="normalized_activities",
                to="core_api.rawpayload",
            ),
        ),
        migrations.AlterField(
            model_name="normalizedactivity",
            name="source_row_index",
            field=models.IntegerField(
                blank=True,
                help_text="Line or element index inside the raw data source",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        help_text="User identity who exported the data", max_length=150
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "export_type",
                    models.CharField(
                        help_text="CSV or XLSX, Download or Email", max_length=50
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                (
                    "source_filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filters applied to the export",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(help_text="SAP / UTILITY / TRAVEL", max_length=50),
                ),
                ("uploaded_by", models.CharField(max_length=150)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_name", models.CharField(max_length=255)),
                ("row_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("status", models.CharField(default="SUCCESS", max_length=50)),
                (
                    "raw_file",
                    models.FileField(blank=True, null=True, upload_to="raw_batches/"),
                ),
                (
                    "raw_payload",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch",
                        to="core_api.rawpayload",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_batches",
                        to="core_api.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="normalized_activities",
                to="core_api.ingestionbatch",
            ),
        ),
    ]
